#!/usr/bin/php 
<?php
/*
 * almajob.php
 * 
 */

require_once('almajob.inc');
require_once('vendor/autoload.php');
use Scriptotek\Alma\Client as AlmaClient;
use Scriptotek\Alma\Sru\Client as SruClient;

#--------------------------------------------------------------
# Main Program
#--------------------------------------------------------------

# Read settings from ini file.
print "Reading Configuration settings from file almajob.ini\n";
$config_file = 'almajob.ini';
$config = parse_ini_file($config_file,true);
$api_key_production = $config['api_key_production'];
$api_key_sandbox = $config['api_key_sandbox'];
$domain  = $config['domain'];

#--------------------------------------------------------------
# Read command line options.
#--------------------------------------------------------------
$shortopts = "";
$longopts = array(
    "name:",
    "instance:",
    "env:",
);

$opts = getopt($shortopts, $longopts);
foreach (array_keys($opts) as $opt) switch ($opt) {
    case 'name':
      $name = $opts['name'];
      break;
    case 'instance':
      $instance = $opts['instance'];
      break;
    case 'env':
      $environment = $opts['env'];
      break;
}

if (empty($name) || empty($instance) || empty($environment)) {
    print "Usage: \n  almajobstatus --env \"{production|sandbox}\" --name \"{Job Name}\" --instance \"{Instance ID}\"\n\n";
    exit(1);
}

if (($environment != 'production') && ($environment != 'sandbox')) {
    print "Usage: \n  almajobstatus --env \"{production|sandbox}\" --name \"{Job Name}\" --instance \"{Instance ID}\"\n\n";
    exit(1);
}

# Set environment API Key.
if ($environment == "production") {
   $api_key = $api_key_production;
}
if ($environment == "sandbox") {
   $api_key = $api_key_sandbox;
}

# Create Alma Client.
$alma = new AlmaClient($api_key, $domain);

# Array to store the list of current jobs.
$jobs = array();

# File to cache array of jobs.
$jobs_cache = ".cache.jobs.$environment";

# Get List of Jobs either by cache or directly from Alma.
# Cache is set for a number of seconds (60 sec * 1440 min) = 1 day.
if (file_exists($jobs_cache) && (filemtime($jobs_cache) > (time() - 60 * 1440 ))) {
    # Retrieve list of jobs from Cache;
    print "Loading Jobs from Cache...\n";
    $jobs = unserialize(file_get_contents($jobs_cache));
} else {
    # Retrieve current list of jobs from Alma:
    print "Loading Jobs from Alma...\n";
    $alma->jobs->setPaginationLimit( 100 );
    foreach ($alma->jobs as $job) {
        array_push($jobs, array('ID' => $job->id,'NAME' => $job->name, 'DESC' => $job->description, 'LINK' => $job->link));
    } 
    file_put_contents($jobs_cache, serialize($jobs), LOCK_EX);
}

#---------------------------------------------
# Get List of Job Statuses
#---------------------------------------------
$statuses = getJobStatuses($alma);

#---------------------------------------------
# Get Job Status
#---------------------------------------------
print "Checking...\n";
print "     Job Name:           '$name'\n";
$key = searchForName($name, $jobs);

$job_id = "";
$job_name = "";
$job_instance = "";

if ($key) {
   $job_id = $jobs[$key]['ID'];
   $job_name = $jobs[$key]['NAME'];
   $job_instance_id = $instance;

   print "     Job ID:             $job_id\n";

   if ($job_id) {
       $job = $alma->jobs[$job_id];

       # Executed Job was:
       print "     Job Instance ID:    $job_instance_id\n";

       # Get Job and Instance Status
       $instance = $job->instances[$job_instance_id];
       $instance->init();
       $instance_info = json_encode($instance);

       $job_submit_time = zuluToLocal($instance->submit_time);
       $job_start_time = zuluToLocal($instance->start_time);
       print "     Job Submited:       $job_submit_time\n";

       $j_status = instanceStatus($api_key, $domain, $job_id, $job_instance_id);
       $desc = $statuses[$j_status];
       print "     Job Status:         $j_status - $desc\n";
   }

} else {
   print "Unable to find job name: $name\n";
   exit(1);
}

print "Done.\n";

?>
