#!/usr/bin/php 
<?php
/*
 * almajoblist.php
 * 
 */

require_once('almajob.inc');
require_once('vendor/autoload.php');
use Scriptotek\Alma\Client as AlmaClient;
use Scriptotek\Alma\Sru\Client as SruClient;

#--------------------------------------------------------------
# Main Program
#--------------------------------------------------------------

# Read settings from ini file.
print "Reading Configuration settings from file almajob.ini\n";
$config_file = 'almajob.ini';
$config = parse_ini_file($config_file,true);
$api_key_production = $config['api_key_production'];
$api_key_sandbox = $config['api_key_sandbox'];
$domain  = $config['domain'];

#--------------------------------------------------------------
# Read command line options.
#--------------------------------------------------------------
$shortopts = "";
$longopts = array(
    "env:",
);

$opts = getopt($shortopts, $longopts);
foreach (array_keys($opts) as $opt) switch ($opt) {
    case 'env':
      $environment = $opts['env'];
      break;
}

if ( empty($environment) ) {
    print "Usage: \n  almajoblist --env \"{production|sandbox}\"\n\n";
    exit(1);
}

if (($environment != 'production') && ($environment != 'sandbox')) {
    print "Usage: \n  almajoblist --env \"{production|sandbox}\"\n\n";
    exit(1);
}

# Set environment API Key.
if ($environment == "production") {
   $api_key = $api_key_production;
}
if ($environment == "sandbox") {
   $api_key = $api_key_sandbox;
}

# Create Alma Client.
$alma = new AlmaClient($api_key, $domain);

# Array to store the list of current jobs.
$jobs = array();

# File to cache array of jobs.
$jobs_cache = ".cache.jobs.$environment";

# Get List of Jobs either by cache or directly from Alma.
# Cache is set for a number of seconds (60 sec * 1440 min) = 1 day.
if (file_exists($jobs_cache) && (filemtime($jobs_cache) > (time() - 60 * 1440 ))) {
    # Retrieve list of jobs from Cache;
    print "Loading Jobs from Cache...\n";
    $jobs = unserialize(file_get_contents($jobs_cache));
} else {
    # Retrieve current list of jobs from Alma:
    print "Loading Jobs from Alma...\n";
    $alma->jobs->setPaginationLimit( 100 );
    foreach ($alma->jobs as $job) {
        array_push($jobs, array('ID' => $job->id,'NAME' => $job->name, 'DESC' => $job->description, 'LINK' => $job->link));
    } 
    file_put_contents($jobs_cache, serialize($jobs), LOCK_EX);
}

#---------------------------------------------
# Get List of Job Statuses
#---------------------------------------------
$statuses = getJobStatuses($alma);

#---------------------------------------------
# Search for job name in list of jobs.
#---------------------------------------------
foreach ($jobs as $job) {
    $job_id = $job['ID'];
    $job_name = $job['NAME'];
    print "ID: $job_id\t\tName: $job_name\n";
}

print "Done.\n";

?>
